/**
 * Fifteen (Sliding Puzzle) Specification
 *
 * SINGLE SOURCE OF TRUTH for the Fifteen puzzle mode.
 *
 * Slide numbered tiles to arrange them in order.
 * Grid sizes: 3x3 (level 1), 4x4 (level 2), 5x5 (level 3).
 * Puzzles generated by random walks from solved state.
 */

import type { ModeSpec } from './types';
import { ACCURACY_PASS_NORMALIZED, GEN_TARGET_PROBABILITY_DEFAULT } from './thresholds';

// =============================================================================
// Mode Color
// =============================================================================

export const MODE_COLOR_FIFTEEN = {
  bg: 'bg-slate-100 dark:bg-slate-500/20',
  border: 'border-slate-200',
  text: 'text-slate-600 dark:text-slate-400',
  accent: 'slate-500',
} as const;

// =============================================================================
// Grid Configs
// =============================================================================

export const FIFTEEN_GRID_CONFIGS = {
  1: { size: 3 },
  2: { size: 4 },
  3: { size: 5 },
} as const;

// =============================================================================
// Fifteen Specification
// =============================================================================

export const FifteenSpec: ModeSpec = {
  metadata: {
    id: 'fifteen',
    displayName: 'Fifteen',
    description: 'Slide numbered tiles to arrange them in order. The classic sliding puzzle.',
    tags: ['training', 'logic', 'spatial'],
    difficultyLevel: 2,
    version: '0.1.0',
  },

  sessionType: 'GameSession',

  scoring: {
    strategy: 'accuracy',
    passThreshold: ACCURACY_PASS_NORMALIZED,
  },

  timing: {
    stimulusDurationMs: 120000, // Self-paced puzzle, 120s time limit
    intervalMs: 1, // Not applicable (puzzle mode)
  },

  generation: {
    generator: 'Sequence',
    targetProbability: GEN_TARGET_PROBABILITY_DEFAULT,
    lureProbability: 0,
    sequenceMode: 'tempo',
  },

  defaults: {
    nLevel: 1,
    trialsCount: 5,
    activeModalities: ['position'],
  },

  adaptivity: {
    algorithm: 'none',
    nLevelSource: 'user',
    configurableSettings: ['nLevel', 'trialsCount'],
  },

  report: {
    sections: ['HERO', 'PERFORMANCE', 'DETAILS', 'RECENT_TREND'],
    display: {
      modeScoreKey: 'report.modeScore.accuracy',
      modeScoreTooltipKey: 'report.modeScore.accuracyTooltip',
      speedStatKey: 'report.speed.reactionTime',
      colors: MODE_COLOR_FIFTEEN,
    },
  },

  stats: {
    simple: {
      sections: ['ACTIVITY_KPIS', 'SESSIONS_PER_DAY', 'PERFORMANCE_KPIS'],
    },
    advanced: {
      sections: ['UPS_SUMMARY'],
    },
  },

  extensions: {
    gridConfigs: FIFTEEN_GRID_CONFIGS,
  },
};

// =============================================================================
// All Fifteen Specs
// =============================================================================

export const FifteenSpecs = {
  fifteen: FifteenSpec,
} as const;
