/**
 * Lights Out Specification
 *
 * SINGLE SOURCE OF TRUTH for the Lights Out puzzle mode.
 *
 * Turn off all cells on a grid by toggling cells and their adjacent neighbours.
 * Grid sizes: 3x3 (easy), 4x4 (medium), 5x5 (hard).
 * Puzzles are guaranteed solvable (generated by reverse-applying random clicks).
 */

import type { ModeSpec } from './types';
import { ACCURACY_PASS_NORMALIZED, GEN_TARGET_PROBABILITY_DEFAULT } from './thresholds';

// =============================================================================
// Mode Color
// =============================================================================

export const MODE_COLOR_LIGHTS_OUT = {
  bg: 'bg-amber-100 dark:bg-amber-500/20',
  border: 'border-amber-200',
  text: 'text-amber-600 dark:text-amber-400',
  accent: 'amber-500',
} as const;

// =============================================================================
// Lights Out Specification
// =============================================================================

export const LightsOutSpec: ModeSpec = {
  metadata: {
    id: 'lights-out',
    displayName: 'Lights Out',
    description:
      'Turn off all lights on a grid. Clicking a cell toggles it and its adjacent neighbours.',
    tags: ['training', 'logic'],
    difficultyLevel: 2,
    version: '0.1.0',
  },

  sessionType: 'GameSession',

  scoring: {
    strategy: 'accuracy',
    passThreshold: ACCURACY_PASS_NORMALIZED,
  },

  timing: {
    stimulusDurationMs: 60000, // Self-paced puzzle, 60s time limit
    intervalMs: 1, // Not applicable (puzzle mode)
  },

  generation: {
    generator: 'Sequence',
    targetProbability: GEN_TARGET_PROBABILITY_DEFAULT,
    lureProbability: 0,
    sequenceMode: 'tempo',
  },

  defaults: {
    nLevel: 3,
    trialsCount: 10,
    activeModalities: ['position'],
  },

  adaptivity: {
    algorithm: 'none',
    nLevelSource: 'user',
    configurableSettings: ['nLevel', 'trialsCount'],
  },

  report: {
    sections: ['HERO', 'PERFORMANCE', 'DETAILS', 'RECENT_TREND'],
    display: {
      modeScoreKey: 'report.modeScore.accuracy',
      modeScoreTooltipKey: 'report.modeScore.accuracyTooltip',
      speedStatKey: 'report.speed.reactionTime',
      colors: MODE_COLOR_LIGHTS_OUT,
    },
  },

  stats: {
    simple: {
      sections: ['ACTIVITY_KPIS', 'SESSIONS_PER_DAY', 'PERFORMANCE_KPIS'],
    },
    advanced: {
      sections: ['UPS_SUMMARY'],
    },
  },
};

// =============================================================================
// All Lights Out Specs
// =============================================================================

export const LightsOutSpecs = {
  'lights-out': LightsOutSpec,
} as const;
