/**
 * Sixteen Specification
 *
 * SINGLE SOURCE OF TRUTH for the Sixteen puzzle mode.
 *
 * Inspired by Simon Tatham's "Sixteen".
 * Slide entire rows left/right or columns up/down (tiles wrap around)
 * to arrange numbered tiles in order (1, 2, 3 ... N²).
 * Grid sizes: 3x3 (level 1), 4x4 (level 2), 5x5 (level 3).
 * Puzzles generated by starting from solved state and applying random shifts.
 */

import type { ModeSpec } from './types';
import { ACCURACY_PASS_NORMALIZED, GEN_TARGET_PROBABILITY_DEFAULT } from './thresholds';

// =============================================================================
// Mode Color
// =============================================================================

export const MODE_COLOR_SIXTEEN = {
  bg: 'bg-zinc-100 dark:bg-zinc-500/20',
  border: 'border-zinc-200',
  text: 'text-zinc-600 dark:text-zinc-400',
  accent: 'zinc-500',
} as const;

// =============================================================================
// Grid Configs
// =============================================================================

export const SIXTEEN_GRID_CONFIGS = {
  1: { size: 3 },
  2: { size: 4 },
  3: { size: 5 },
} as const;

// =============================================================================
// Sixteen Specification
// =============================================================================

export const SixteenSpec: ModeSpec = {
  metadata: {
    id: 'sixteen',
    displayName: 'Sixteen',
    description:
      'Slide entire rows and columns to arrange numbered tiles in order. Tiles wrap around edges.',
    tags: ['training', 'spatial', 'logic'],
    difficultyLevel: 2,
    version: '0.1.0',
  },

  sessionType: 'GameSession',

  scoring: {
    strategy: 'accuracy',
    passThreshold: ACCURACY_PASS_NORMALIZED,
  },

  timing: {
    stimulusDurationMs: 120000, // Self-paced puzzle, 120s time limit
    intervalMs: 1, // Not applicable (puzzle mode)
  },

  generation: {
    generator: 'Sequence',
    targetProbability: GEN_TARGET_PROBABILITY_DEFAULT,
    lureProbability: 0,
    sequenceMode: 'tempo',
  },

  defaults: {
    nLevel: 1,
    trialsCount: 5,
    activeModalities: ['position'],
  },

  adaptivity: {
    algorithm: 'none',
    nLevelSource: 'user',
    configurableSettings: ['nLevel', 'trialsCount'],
  },

  report: {
    sections: ['HERO', 'PERFORMANCE', 'DETAILS', 'RECENT_TREND'],
    display: {
      modeScoreKey: 'report.modeScore.accuracy',
      modeScoreTooltipKey: 'report.modeScore.accuracyTooltip',
      speedStatKey: 'report.speed.reactionTime',
      colors: MODE_COLOR_SIXTEEN,
    },
  },

  stats: {
    simple: {
      sections: ['ACTIVITY_KPIS', 'SESSIONS_PER_DAY', 'PERFORMANCE_KPIS'],
    },
    advanced: {
      sections: ['UPS_SUMMARY'],
    },
  },

  extensions: {
    gridConfigs: SIXTEEN_GRID_CONFIGS,
  },
};

// =============================================================================
// All Sixteen Specs
// =============================================================================

export const SixteenSpecs = {
  sixteen: SixteenSpec,
} as const;
