/**
 * Twiddle Specification
 *
 * SINGLE SOURCE OF TRUTH for the Twiddle puzzle mode.
 *
 * Arrange numbered tiles in order by rotating 2x2 groups clockwise.
 * Grid sizes: 3x3 (level 1), 4x4 (level 2), 5x5 (level 3).
 * Puzzles are generated by starting from solved state and applying random rotations.
 */

import type { ModeSpec } from './types';
import { ACCURACY_PASS_NORMALIZED, GEN_TARGET_PROBABILITY_DEFAULT } from './thresholds';

// =============================================================================
// Mode Color
// =============================================================================

export const MODE_COLOR_TWIDDLE = {
  bg: 'bg-fuchsia-100 dark:bg-fuchsia-500/20',
  border: 'border-fuchsia-200',
  text: 'text-fuchsia-600 dark:text-fuchsia-400',
  accent: 'fuchsia-500',
} as const;

// =============================================================================
// Twiddle Specification
// =============================================================================

export const TwiddleSpec: ModeSpec = {
  metadata: {
    id: 'twiddle',
    displayName: 'Twiddle',
    description: 'Arrange numbered tiles in order by rotating 2x2 groups clockwise.',
    tags: ['training', 'spatial', 'logic'],
    difficultyLevel: 2,
    version: '0.1.0',
  },

  sessionType: 'GameSession',

  scoring: {
    strategy: 'accuracy',
    passThreshold: ACCURACY_PASS_NORMALIZED,
  },

  timing: {
    stimulusDurationMs: 60000, // Self-paced puzzle, 60s time limit
    intervalMs: 1, // Not applicable (puzzle mode)
  },

  generation: {
    generator: 'Sequence',
    targetProbability: GEN_TARGET_PROBABILITY_DEFAULT,
    lureProbability: 0,
    sequenceMode: 'tempo',
  },

  defaults: {
    nLevel: 1,
    trialsCount: 5,
    activeModalities: ['position'],
  },

  adaptivity: {
    algorithm: 'none',
    nLevelSource: 'user',
    configurableSettings: ['nLevel', 'trialsCount'],
  },

  report: {
    sections: ['HERO', 'PERFORMANCE', 'DETAILS', 'RECENT_TREND'],
    display: {
      modeScoreKey: 'report.modeScore.accuracy',
      modeScoreTooltipKey: 'report.modeScore.accuracyTooltip',
      speedStatKey: 'report.speed.reactionTime',
      colors: MODE_COLOR_TWIDDLE,
    },
  },

  stats: {
    simple: {
      sections: ['ACTIVITY_KPIS', 'SESSIONS_PER_DAY', 'PERFORMANCE_KPIS'],
    },
    advanced: {
      sections: ['UPS_SUMMARY'],
    },
  },
};

// =============================================================================
// All Twiddle Specs
// =============================================================================

export const TwiddleSpecs = {
  twiddle: TwiddleSpec,
} as const;
