import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';

export default {
  darkMode: 'class',
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    './index.html',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      screens: {
        xs: '375px',
      },
      colors: {
        // Override slate with warm grays (Woven Ink palette)
        slate: {
          50: '#F0EEE9' /* Warm paper - matches bg-app */,
          100: '#F5F4F1' /* Light warm */,
          200: '#E8E6E1' /* Warm border */,
          300: '#D4D2CA' /* Warm divider - matches border */,
          400: '#9A958D' /* Warm muted */,
          500: '#787570' /* Medium warm */,
          600: '#5A5550' /* Warm charcoal */,
          700: '#3A3835' /* Dark warm */,
          800: '#252320' /* Very dark warm */,
          900: '#1A1815' /* Ink */,
          950: '#0F0E0D' /* Deep ink */,
        },
        // Override accent colors with warm Woven Ink versions
        violet: {
          50: '#F8F6F5' /* Warm mauve bg */,
          100: '#F0EDEB',
          200: '#E0DAD6',
          300: '#C8BFB8',
          400: '#A8988C',
          500: '#857468' /* Warm mauve mid */,
          600: '#6B5D53' /* Warm mauve text */,
          700: '#544840',
          800: '#3E3632',
          900: '#2A2523',
          950: '#1A1815',
        },
        orange: {
          50: '#FAF7F5' /* Warm terracotta bg */,
          100: '#F5EFEA',
          200: '#EBE0D5',
          300: '#D9C8B8',
          400: '#C4A890',
          500: '#A68568' /* Warm terracotta mid */,
          600: '#8B6B50' /* Warm terracotta text */,
          700: '#6E5340',
          800: '#523E32',
          900: '#362A24',
          950: '#1A1815',
        },
        pink: {
          50: '#F9F6F6' /* Warm dusty rose bg */,
          100: '#F2EDEC',
          200: '#E5DAD8',
          300: '#D1C0BC',
          400: '#B89E98',
          500: '#967B75' /* Warm dusty rose mid */,
          600: '#7A615B' /* Warm dusty rose text */,
          700: '#5F4A46',
          800: '#463836',
          900: '#2E2624',
          950: '#1A1815',
        },
        teal: {
          50: '#F5F7F6' /* Warm sage bg */,
          100: '#ECF0ED',
          200: '#D8E0DA',
          300: '#B8C8BD',
          400: '#8FA899',
          500: '#688575' /* Warm sage mid */,
          600: '#526B5C' /* Warm sage text */,
          700: '#405248',
          800: '#323D38',
          900: '#242A27',
          950: '#151815',
        },
        blue: {
          50: '#F5F6F7' /* Warm slate-blue bg */,
          100: '#ECEEEF',
          200: '#D8DCDF',
          300: '#B8C0C5',
          400: '#909CA3',
          500: '#6B7880' /* Warm slate-blue mid */,
          600: '#556068' /* Warm slate-blue text */,
          700: '#424A50',
          800: '#32383C',
          900: '#242728',
          950: '#151618',
        },
        cyan: {
          50: '#F5F7F7' /* Warm teal-gray bg */,
          100: '#ECF0EF',
          200: '#D8E0DE',
          300: '#B8C8C4',
          400: '#90A8A2',
          500: '#688580' /* Warm teal-gray mid */,
          600: '#526B66' /* Warm teal-gray text */,
          700: '#40524E',
          800: '#323D3B',
          900: '#242A28',
          950: '#151816',
        },
        amber: {
          50: '#FAF8F5' /* Warm amber bg */,
          100: '#F5F0E8',
          200: '#EBE0D0',
          300: '#DCC8A8',
          400: '#C8A878',
          500: '#A88850' /* Warm amber mid */,
          600: '#8B6D3D' /* Warm amber text */,
          700: '#6B5330',
          800: '#503D25',
          900: '#35281A',
          950: '#1A1510',
        },
        emerald: {
          50: '#F5F8F6' /* Warm forest bg */,
          100: '#ECF2EE',
          200: '#D5E3DA',
          300: '#B0CCB8',
          400: '#7FAA8A',
          500: '#5A8862' /* Warm forest mid */,
          600: '#456B4C' /* Warm forest text */,
          700: '#35523B',
          800: '#283D2D',
          900: '#1C2A1F',
          950: '#101812',
        },
        // SHADCN TOKENS
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // NEURODUAL TOKENS (format channel pour support opacité bg-visual/50)
        surface: 'hsl(var(--neuro-bg-surface) / <alpha-value>)',
        visual: 'hsl(var(--neuro-accent-visual) / <alpha-value>)',
        audio: 'hsl(var(--neuro-accent-audio) / <alpha-value>)',
        danger: 'hsl(var(--neuro-accent-danger) / <alpha-value>)',
        // INK PALETTE (warm tones)
        ink: {
          DEFAULT: '#1A1815' /* Primary ink color */,
          light: '#5A5550' /* Warm charcoal */,
          paper: '#FAF9F6' /* Warm paper */,
          muted: '#787570' /* Warm gray */,
        },
        // WOVEN INK THEME (Game pages)
        woven: {
          bg: 'hsl(var(--woven-bg) / <alpha-value>)',
          surface: 'hsl(var(--woven-surface) / <alpha-value>)',
          grid: 'hsl(var(--woven-grid) / <alpha-value>)',
          cell: {
            rest: 'hsl(var(--woven-cell-rest) / <alpha-value>)',
            active: 'hsl(var(--woven-cell-active) / <alpha-value>)',
          },
          border: 'hsl(var(--woven-border) / <alpha-value>)',
          weave: 'hsl(var(--woven-weave) / <alpha-value>)',
          text: {
            DEFAULT: 'hsl(var(--woven-text) / <alpha-value>)',
            muted: 'hsl(var(--woven-text-muted) / <alpha-value>)',
          },
          correct: 'hsl(var(--woven-correct) / <alpha-value>)',
          incorrect: 'hsl(var(--woven-incorrect) / <alpha-value>)',
          blue: 'hsl(var(--woven-blue) / <alpha-value>)',
          amber: 'hsl(var(--woven-amber) / <alpha-value>)',
          orange: 'hsl(var(--woven-orange) / <alpha-value>)',
          cyan: 'hsl(var(--woven-cyan) / <alpha-value>)',
          purple: 'hsl(var(--woven-purple) / <alpha-value>)',
          magenta: 'hsl(var(--woven-magenta) / <alpha-value>)',
          gray: 'hsl(var(--woven-gray) / <alpha-value>)',
          focus: 'hsl(var(--woven-focus) / <alpha-value>)',
        },
        vivid: {
          gray: 'hsl(var(--vivid-gray) / <alpha-value>)',
          red: 'hsl(var(--vivid-red) / <alpha-value>)',
          blue: 'hsl(var(--vivid-blue) / <alpha-value>)',
          green: 'hsl(var(--vivid-green) / <alpha-value>)',
          yellow: 'hsl(var(--vivid-yellow) / <alpha-value>)',
          purple: 'hsl(var(--vivid-purple) / <alpha-value>)',
          orange: 'hsl(var(--vivid-orange) / <alpha-value>)',
          cyan: 'hsl(var(--vivid-cyan) / <alpha-value>)',
          magenta: 'hsl(var(--vivid-magenta) / <alpha-value>)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      spacing: {
        'safe-top': 'env(safe-area-inset-top, 20px)',
        'safe-bottom': 'env(safe-area-inset-bottom, 20px)',
        'safe-left': 'env(safe-area-inset-left, 0px)',
        'safe-right': 'env(safe-area-inset-right, 0px)',
      },
    },
  },
  plugins: [animate],
} satisfies Config;
