// @ts-nocheck
/**
 * Sixteen puzzle generator — faithful port of Simon Tatham's sixteen.c
 *
 * "16-puzzle": a sliding-tiles jigsaw which differs from the 15-puzzle
 * in that you toroidally rotate a row or column at a time.
 *
 * Tiles are 1-indexed (1..w*h). The solved state is [1, 2, 3, ..., w*h].
 *
 * Source: https://git.tartarus.org/?p=simon/puzzles.git;a=blob;f=sixteen.c
 */

// ---------------------------------------------------------------------------
// Result type
// ---------------------------------------------------------------------------

export interface SixteenPuzzle {
  /** Flat row-major array of tile values, 1-indexed (1..w*h). */
  tiles: number[];
  /** Grid width. */
  w: number;
  /** Grid height. */
  h: number;
}

// ---------------------------------------------------------------------------
// Ported from sixteen.c — perm_parity()
// ---------------------------------------------------------------------------

/**
 * Compute the parity of a permutation (0 = even, 1 = odd).
 * Counts the number of inversions mod 2.
 *
 * Faithful port of:
 * ```c
 * static int perm_parity(int *perm, int n)
 * ```
 */
function permParity(perm: number[], n: number): number {
  let ret = 0;

  for (let i = 0; i < n - 1; i++) {
    for (let j = i + 1; j < n; j++) {
      if (perm[i] > perm[j]) ret = ret ? 0 : 1;
    }
  }

  return ret;
}

// ---------------------------------------------------------------------------
// RNG helper — maps to Tatham's random_upto()
// ---------------------------------------------------------------------------

function randomUpto(n: number): number {
  return Math.floor(Math.random() * n);
}

// ---------------------------------------------------------------------------
// Ported from sixteen.c — new_game_desc()
// ---------------------------------------------------------------------------

/**
 * Generate a solvable sixteen-puzzle of the given dimensions.
 *
 * Faithful port of `new_game_desc()` from Tatham's sixteen.c.
 *
 * When `movetarget` is provided (> 0), the puzzle is generated by
 * applying exactly that many random row/column shifts to the solved
 * state (the "shuffle" path). This path includes Tatham's logic to
 * avoid boring sequences (direct undos, repeated moves that are
 * equivalent to fewer moves in the opposite direction).
 *
 * When `movetarget` is 0 (or omitted), the puzzle is generated by
 * a random permutation with a parity constraint: if both w and h
 * are odd, the permutation must have even parity (otherwise the
 * puzzle is unsolvable). The last two tiles are swapped if necessary
 * to satisfy the constraint.
 *
 * @param w — grid width. Must be >= 2.
 * @param h — grid height. Must be >= 2.
 * @param movetarget — optional number of shuffle moves. 0 = random permutation.
 */
export function generateSixteenPuzzle(w: number, h: number, movetarget: number = 0): SixteenPuzzle {
  if (w < 2 || h < 2) {
    throw new RangeError('Width and height must both be at least two');
  }

  const n = w * h;
  const tiles: number[] = new Array(n);

  if (movetarget) {
    // -----------------------------------------------------------------
    // Shuffle path: start solved, apply movetarget random moves.
    // Faithful port of the movetarget branch of new_game_desc().
    // -----------------------------------------------------------------

    let prevoffset = -1;
    const max = w > h ? w : h;
    const prevmoves: number[] = new Array(max).fill(0);

    // Start with solved state: tiles[i] = i (0-indexed internally)
    for (let i = 0; i < n; i++) tiles[i] = i;

    for (let i = 0; i < movetarget; i++) {
      let start: number;
      let offset: number;
      let len: number;
      let direction: number;
      let index: number;

      // Choose a move to make, avoiding boring undos.
      while (true) {
        const j = randomUpto(w + h);

        if (j < w) {
          // Column
          index = j;
          start = j;
          offset = w;
          len = h;
        } else {
          // Row
          index = j - w;
          start = index * w;
          offset = 1;
          len = w;
        }

        direction = -1 + 2 * randomUpto(2);

        /*
         * To at least _try_ to avoid boring cases, check
         * that this move doesn't directly undo a previous
         * one, or repeat it so many times as to turn it
         * into fewer moves in the opposite direction.
         */
        if (offset === prevoffset) {
          const tmp = prevmoves[index] + direction;
          if (Math.abs(2 * tmp) > len || Math.abs(tmp) < Math.abs(prevmoves[index])) {
            continue;
          }
        }

        // Found an OK move to make.
        if (offset !== prevoffset) {
          for (let k = 0; k < max; k++) prevmoves[k] = 0;
          prevoffset = offset;
        }
        prevmoves[index] += direction;
        break;
      }

      // Make the move.
      if (direction < 0) {
        start += (len - 1) * offset;
        offset = -offset;
      }
      const tmp = tiles[start];
      for (let j = 0; j + 1 < len; j++) {
        tiles[start + j * offset] = tiles[start + (j + 1) * offset];
      }
      tiles[start + (len - 1) * offset] = tmp;
    }
  } else {
    // -----------------------------------------------------------------
    // Random-permutation path with parity constraint.
    // Faithful port of the else branch of new_game_desc().
    // -----------------------------------------------------------------

    const used: boolean[] = new Array(n).fill(false);
    for (let i = 0; i < n; i++) tiles[i] = -1;

    /*
     * If both dimensions are odd, there is a parity constraint.
     */
    const stop = w & h & 1 ? 2 : 0;

    /*
     * Place everything except (possibly) the last two tiles.
     */
    let x = 0;
    for (let i = n; i > stop; i--) {
      const k0 = i > 1 ? randomUpto(i) : 0;
      let k = k0;

      let j = 0;
      for (; j < n; j++) {
        if (!used[j] && k-- === 0) break;
      }

      used[j] = true;

      while (tiles[x] >= 0) x++;
      tiles[x] = j;
    }

    if (stop) {
      /*
       * Find the last two locations, and the last two pieces.
       */
      while (tiles[x] >= 0) x++;
      const x1 = x;
      x++;
      while (tiles[x] >= 0) x++;
      const x2 = x;

      let p1 = 0;
      for (let i = 0; i < n; i++) {
        if (!used[i]) {
          p1 = i;
          break;
        }
      }
      let p2 = 0;
      for (let i = p1 + 1; i < n; i++) {
        if (!used[i]) {
          p2 = i;
          break;
        }
      }

      /*
       * Try the last two tiles one way round. If that fails, swap them.
       */
      tiles[x1] = p1;
      tiles[x2] = p2;
      if (permParity(tiles, n) !== 0) {
        tiles[x1] = p2;
        tiles[x2] = p1;
      }
    }
  }

  // Convert from 0-indexed internal to 1-indexed output (tiles[i]+1),
  // matching Tatham's output format.
  for (let i = 0; i < n; i++) tiles[i] = tiles[i] + 1;

  return { tiles, w, h };
}
