export {
  // Constants
  CALIBRATION_MODALITIES,
  CALIBRATION_SEQUENCE,
  TRAINING_SEQUENCE,
  CALIBRATION_DERIVED_MODES,
  TOTAL_CALIBRATION_STEPS,
  NBACK_BLOCK_SIZE,
  DUAL_TRACK_BLOCK_SIZE,
  DUAL_TRACK_CALIBRATION_TRACKING_MS,
  MAX_BLOCKS_PER_STEP,
  THRESHOLD_UP,
  THRESHOLD_DOWN,
  CALIBRATION_MIN_LEVEL,
  CALIBRATION_MAX_LEVEL,
  START_LEVEL,
  DUAL_TRACK_BALL_CONFIG,
  DUAL_TRACK_BALL_CONFIG_SMALL,
  ROLLING_WINDOW,
  NBACK_DPRIME_UP,
  NBACK_DPRIME_DOWN,
  DT_ACCURACY_UP,
  DT_ACCURACY_DOWN,
  STAIRCASE_MAX_ROUNDS,
  STAIRCASE_FAIL_THRESHOLD,
  DEFAULT_MODALITY_STATE,
  DEFAULT_CALIBRATION_STATE,
  DEFAULT_STAIRCASE_STATE,
  // Staircase calibration (intra-session)
  type StaircaseState,
  applyStaircaseRound,
  // Types
  type CalibrationModality,
  type CalibrationGameMode,
  type CalibrationStep,
  type CalibrationPhase,
  type CalibrationState,
  type CalibrationEvent,
  type CalibrationBaselineFact,
  type CalibrationResetFact,
  type CalibrationSessionFact,
  type CalibrationProjectionFacts,
  type ModalityCalibrationState,
  // Strategy interfaces
  type CalibrationStrategy,
  type ProgressionStrategy,
  // Default strategy instances
  jaeggiCalibrationStrategy,
  rollingWindowProgressionStrategy,
  // Strategy swap (developer-only)
  setCalibrationStrategy,
  setProgressionStrategy,
  getCalibrationStrategy,
  getProgressionStrategy,
  // Game mode UI config
  type CalibrationGameModeConfig,
  getGameModeConfig,
  getActiveGameModeConfigs,
  // Sequence builder
  buildCalibrationSequence,
  // Helpers
  resultKey,
  getResult,
  getCalibrationProgress,
  getCurrentCalibrationStep,
  getMasteredLevel,
  getBlockSize,
  getDualTrackBallConfig,
  rollingAverage,
  // Algorithm (delegates to active strategy)
  applyBlockResult,
  shouldLevelUp,
  shouldLevelDown,
  computeProgress,
  findNextIncompleteStep,
  isCalibrationCompleteWithExclusions,
  applyCalibrationEvent,
  reduceCalibrationEvents,
  projectCalibrationProfileFromFacts,
  // Profile computation
  computeGlobalScore,
  findModalityExtremes,
  // Modality mapping tables & labels
  CALIBRATION_MODALITY_LABELS,
  MODALITY_TO_DT_IDENTITY,
  MODALITY_TO_NB_MODALITIES,
  // Score & evidence helpers
  getCalibrationStepScore,
  getSharedModalityLevel,
  type ModalityEvidenceStatus,
  getModalityEvidenceStatus,
  getCalibrationSessionScore,
  // Play config builder
  type CalibrationPlayConfig,
  buildCalibrationPlayConfig,
  // Progression scheduler
  type NextTrainingSession,
  pickNextTrainingSession,
} from './calibration-algorithm';
