export type SessionEndEventType =
  | 'SESSION_ENDED'
  | 'SESSION_IMPORTED'
  | 'RECALL_SESSION_ENDED'
  | 'FLOW_SESSION_ENDED'
  | 'DUAL_PICK_SESSION_ENDED'
  | 'TRACE_SESSION_ENDED'
  | 'TIME_SESSION_ENDED'
  | 'MOT_SESSION_ENDED'
  | 'CORSI_SESSION_ENDED'
  | 'OSPAN_SESSION_ENDED'
  | 'RUNNING_SPAN_SESSION_ENDED'
  | 'PASAT_SESSION_ENDED'
  | 'SWM_SESSION_ENDED'
  | 'COGNITIVE_TASK_SESSION_ENDED';

export const SESSION_END_EVENT_TYPES_ARRAY = [
  'SESSION_ENDED',
  'SESSION_IMPORTED',
  'RECALL_SESSION_ENDED',
  'FLOW_SESSION_ENDED',
  'DUAL_PICK_SESSION_ENDED',
  'TRACE_SESSION_ENDED',
  'TIME_SESSION_ENDED',
  'MOT_SESSION_ENDED',
  'CORSI_SESSION_ENDED',
  'OSPAN_SESSION_ENDED',
  'RUNNING_SPAN_SESSION_ENDED',
  'PASAT_SESSION_ENDED',
  'SWM_SESSION_ENDED',
  'COGNITIVE_TASK_SESSION_ENDED',
] as const satisfies readonly SessionEndEventType[];

export const SESSION_END_EVENT_TYPES: ReadonlySet<SessionEndEventType> = new Set(
  SESSION_END_EVENT_TYPES_ARRAY,
);

export function isSessionEndEventType(value: string): value is SessionEndEventType {
  return (SESSION_END_EVENT_TYPES_ARRAY as readonly string[]).includes(value);
}
