export type SessionStartEventType =
  | 'SESSION_STARTED'
  | 'RECALL_SESSION_STARTED'
  | 'FLOW_SESSION_STARTED'
  | 'DUAL_PICK_SESSION_STARTED'
  | 'TRACE_SESSION_STARTED'
  | 'TIME_SESSION_STARTED'
  | 'MOT_SESSION_STARTED'
  | 'CORSI_SESSION_STARTED'
  | 'OSPAN_SESSION_STARTED'
  | 'RUNNING_SPAN_SESSION_STARTED'
  | 'PASAT_SESSION_STARTED'
  | 'SWM_SESSION_STARTED'
  | 'COGNITIVE_TASK_SESSION_STARTED';

export const SESSION_START_EVENT_TYPES_ARRAY = [
  'SESSION_STARTED',
  'RECALL_SESSION_STARTED',
  'FLOW_SESSION_STARTED',
  'DUAL_PICK_SESSION_STARTED',
  'TRACE_SESSION_STARTED',
  'TIME_SESSION_STARTED',
  'MOT_SESSION_STARTED',
  'CORSI_SESSION_STARTED',
  'OSPAN_SESSION_STARTED',
  'RUNNING_SPAN_SESSION_STARTED',
  'PASAT_SESSION_STARTED',
  'SWM_SESSION_STARTED',
  'COGNITIVE_TASK_SESSION_STARTED',
] as const satisfies readonly SessionStartEventType[];

export const SESSION_START_EVENT_TYPES: ReadonlySet<string> = new Set(
  SESSION_START_EVENT_TYPES_ARRAY,
);

export function isSessionStartEventType(value: string): value is SessionStartEventType {
  return (SESSION_START_EVENT_TYPES_ARRAY as readonly string[]).includes(value);
}
